# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

files: "src/LintTest/Python"
exclude: "(^docs/)|(yaml$)|src/tests"
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  # See https://black.readthedocs.io/en/stable/integrations/source_version_control.html for more information
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: v23.9.1
    hooks:
      - id: black
        language_version: python3.9
        args:
          - "--line-length=120"

  # See https://hadialqattan.github.io/pycln/#/?id=version-control-integration for more information
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        args: ["--max-line-length", "120"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort-python
        # Use black profile for isort to avoid conflicts
        # see https://github.com/PyCQA/isort/issues/1518
        args: ["--profile", "black", --line-length=120]
