name: GitHub Action Unit Test
run-name: Run Unit Test on Branch ${{ github.ref }}
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run Unit Test Successfully
        run: |
          echo "Unit Test"
      - run: cd ${{ github.workspace }}/src/TestingDemo/DemoLibrary.Tests
      - run: dotnet test
