name: GitHub Action Selenium Test
run-name: ${{ github.actor }} Run Unit Test on Branch ${{ github.ref }}
on: [push]
jobs:
  Selenium-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/src/SeleniumTest
          pip install -r requirements.txt
          python Program.py
