name: Python flake8 Lint
run-name: ${{ github.actor }} is running flake8 Lint on ${{ github.ref }}

on: [push, pull_request, workflow_dispatch]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src/LintTest/Python"
          max-line-length: "80"
          update-pip: "true"
